<p class = "my_content">There are all active activiy point</p>
<div class="responsive-table">
    <table>
    <col style="width: 13%;" />
    <col style="width: 14%;" />
    <col style="width: 9%;" />
    <col style="width: 12%;" />
    <col style="width: 11%;" />
    <col style="width: 11%;" />
    <col style="width: 9%;" />
    <col style="width: 10%;" />
    <col style="width: 11%;" />
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Point</th>
                <th>Goal</th>
                <th>Start</th>
                <th>End</th>
                <th>Priority</th>
                <th>Overlap</th>
                <th>Process</th>
            </tr>
        </thead>
        <tbody>
        <?php
            /**
             * @var \LoyaltyProgram\RewardPoint\Block\AllActivity $block
             */

            // echo $block->sayHello();

            // $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            // $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
            // $connection = $resource->getConnection();
            // $tableEarn = $resource->getTableName('earn'); //gives table name
            // $tableGoal = $resource->getTableName('goal'); //gives table name
            

            // $sqlEarn = $connection->select('*')->from($tableEarn)->join(
            //     $tableGoal, 
            //     $tableEarn . '.goal_id = ' . $tableGoal . '.goal_id'
            // );
            
            // foreach ($connection->fetchAll($sqlEarn) as $row){   
            // echo "<tr>";
            // echo "<td>" . $row['earn_name'] . "</td>";
            // echo "<td>" . $row['earn_description'] . "</td>";
            // echo "<td>" . $row['earn_point'] . "</td>";
            // if ($row['goal_type'] == "Order") $s_start = "Buy";
            // else $s_start = "Spend";
            // echo "<td>" . $s_start . " " . $row['goal_number'] . " " . $row['goal_type'] . "</td>";
            // echo "<td>" . $row['earn_start'] . "</td>";
            // echo "<td>" . $row['earn_end'] . "</td>";
            // echo "</tr>"; 
            // }

            $servername = "localhost";
            $username = "root";
            $password = "";
            $dbname = "magento241";

            // Create connection
            $conn = new mysqli($servername, $username, $password, $dbname);
            // Check connection
            if ($conn->connect_error) {
            die("Connection failed: " . $conn->connect_error);
            }
            $sqlP = "SELECT * FROM earn, goal, process WHERE earn.goal_id = goal.goal_id AND earn.earn_id = process.earn_id AND process.entity_id = ". $block->getCustomerId();
            $resultP = $conn->query($sqlP);
            
            $ids;
            if ($resultP->num_rows > 0) {
                while($rowP = $resultP->fetch_assoc()){
                    $dataP[] = $rowP;
                    $ids[] = $rowP['earn_id'];
                }
            }
            
            $sql = "SELECT * FROM earn, goal WHERE earn.goal_id = goal.goal_id";
            $result = $conn->query($sql);

            if ($result->num_rows > 0) {
            // output data of each row
            while($row = $result->fetch_assoc()) {
                if ($row['earn_id'] != 10) {
                if ($row['earn_actived']) {
                echo "<tr>";
                echo "<td>" . $row['earn_name'] . "</td>";
                echo "<td>" . $row['earn_description'] . "</td>";
                echo "<td>" . $row['earn_point'] . "</td>";
                if ($row['goal_type'] == "Order") $s_start = "Buy";
                else $s_start = "Spend";
                echo "<td>" . $s_start . " " . $row['goal_number'] . " " . $row['goal_type'] . "</td>";
                echo "<td>" . $row['earn_start'] . "</td>";
                echo "<td>" . $row['earn_end'] . "</td>";
                echo "<td>" . $row['earn_priority'] . "</td>";
                if ($row['earn_overlap']) $overlap = "Yes";
                else $overlap = "No";
                echo "<td>" . $overlap. "</td>";
                

                if ($row['earn_id'] != 11) {
                    if (empty($ids)) {
                        echo "<td> 0/" . $row['goal_number'] . "</td>";
                    } else {
                        $check = array_search($row['earn_id'], $ids);
                        if (in_array($row['earn_id'], $ids)){
                            if ($dataP[$check]['process_activity'] == $row['goal_number']) {
                                echo "<td>" . $dataP[$check]['process_activity'] . "/" . $row['goal_number'] . " (done)</td>";
                            } else echo "<td>" . $dataP[$check]['process_activity'] . "/" . $row['goal_number'] . "</td>";
                        } else  echo "<td> 0/" . $row['goal_number'] . "</td>";
                    }
                    echo "</tr>"; 
                    }
                }    
            }
            }
            } else {
            echo "0 results";
            }
            $conn->close();



        ?>
        </tbody>
    </table>
</div>
